const post_schema = "CREATE TABLE POST("+
	"PostNum INT NOT NULL AUTO_INCREMENT UNIQUE,"+
	" Email VARCHAR(100) NOT NULL,"+
	" BlogID INT NOT NULL,"+
	" Archived BOOLEAN,"+
	" Title VARCHAR(150) NOT NULL,"+
	" Text LONGTEXT NOT NULL,"+
	" Time TIMESTAMP,"+
	" PRIMARY KEY (PostNum, BlogID, Email),"+
	" FOREIGN KEY (Email) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE NO ACTION,"+
	" FOREIGN KEY(BlogID) REFERENCES BLOG(BlogID) ON DELETE CASCADE ON UPDATE NO ACTION)";

exports.post_schema = post_schema;
